---
title: "In-class Exercise 6"
author: "chandru"
---
##Loading the required the packages

```{r}
pacman::p_load(spdep, tmap, sf, knitr, 
               ggpubr, cluster, factoextra, NbClust,
               heatmaply, corrplot, psych, tidyverse, GGally)
```

##Importing Data

```{r}

mpsz <- st_read("../In-class_Ex06/data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML (2).kml")

```

```{r}
extract_kml_field <- function(html_text, field_name) {
  if (is.na(html_text) || html_text == "") return(NA_character_)
  
  page <- read_html(html_text)
  rows <- page %>% html_elements("tr")
  
  value <- rows %>%
    keep(~ html_text2(html_element(.x, "th")) == field_name) %>%
    html_element("td") %>%
    html_text2()
  
  if (length(value) == 0) NA_character_ else value
}
```



```{r}
mpsz
```
0-D Bus Trips

```{r}

odbus <- read_csv("../In-class_Ex06/data/aspatial/origin_destination_bus_202508.csv")

```
```{r}

BusStop <- st_read(dsn = "../In-class_Ex06/data/geospatial/BusStopLocation_Aug2025",layer = "BusStop")

```

```{r}
BusStop <- st_transform(BusStop, crs =3414)

BusStop
```

```{r}
mpsz<- st_transform(mpsz, crs =3414)

mpsz
```


```{r}
tm_shape(mpsz) + tm_polygons() + tm_shape(BusStop) + tm_dots()
```
##Extracting Bus Stops within Singapore

```{r}

BusStop_in_SG <- st_join( BusStop,mpsz, join=st_within,left=FALSE)
```

```{r}
tm_shape(mpsz) + tm_polygons() + tm_shape(BusStop_in_SG) + tm_dots()
```

##Deriving Analytical Hexagon

```{r}

hexagon <- st_make_grid(mpsz, cellsize=700, what='polygon', square= FALSE) %>% st_sf()
```






##Filtering hexagons with bus stops

```{r}

hexagon$n_collisions= lengths(st_intersects(hexagon,BusStop_in_SG))

hexagon <- filter(hexagon, n_collisions >0)
```


##Assigning ids to each Hexagon

```{r}
hexagon <- hexagon %>% select(, -n_collisions)

hexagon$HEX_ID <- sprintf("H%04d", seq_len(nrow(hexagon))) %>% as.factor()

kable(head(hexagon))
```
##Preparing Trip Generation Data

```{r}
trips <- odbus %>%
  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%
  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%
  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%
  rename(TRIPS = TOTAL_TRIPS)

trips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)

kable(head(trips))
```

```{r}
bs_hex <- st_intersection(
  BusStop, hexagon
) %>%
  st_drop_geometry() %>%
  select(c(BUS_STOP_N, HEX_ID))

kable(head(bs_hex))
```

## Adding HEX_ID into bus trips data

```{r}
trips <- inner_join(trips, bs_hex)
kable(head(trips))
```

