---
title: "In class exercise 3b"
---

```{r}
pacman::p_load(sf, tmap, tidyverse, rvest,httr)
```

```{r}
folder_path<-"data/aspatial/acra"
file_list<-list.files(path=folder_path,pattern ="^ACRA*.*\\.csv$",full.names=TRUE)


acra_data <-file_list %>%
  map_dfr(read_csv)
```

Saving ACRA data

```{r}
write_rds(acra_data,"data/rds/acra_data.rds")
```

Tidying ACRA data Write a code chunk to perfrom the followings

-   select the target business by using SSIC code,

-   derive the year and month fields from registration_incorporation_date
```{r}
biz_5611 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code == 56111) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM =month(date),
         MONTH_ABBR=month(date,
                          label =TRUE,
                          abbr = TRUE)) %>%
  mutate(
    postal_code=str_pad(postal_code,
    width=6, side="left", pad ="0")) %>%
            filter(YEAR == 2025)
```

Geocoding

```{r}
postcodes <- unique(biz_5611$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"

found <- data.frame()
not_found <- data.frame(postcode = character())

for (pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "Y",
    pageNum = "1"
  )
  
  res <- GET(url, query = query)
  json <- content(res)
  
  if (json$found != 0){
    df <- as.data.frame(json$results, stringsAsFactors = FALSE)
    df$input_postcode <- pc
    found <- bind_rows(found, df)
  } else {
    not_found <- bind_rows(not_found, data.frame(postcode = pc))
  }
}

```

Appending the location info


```{r}
biz_5611=biz_5611 %>%
  left_join(found, by=c('postal_code'='POSTAL'))
```


converting into SF data frame
```{r}

biz_5611<- st_as_sf(biz_5611, coords=c("X","Y"),crs=3414)
```
