---
title: "In-class Exercise 5"
author: "Chandru"
---

```{r}
pacman::p_load(sf, ggstatsplot, tmap, tidyverse, knitr, sfdep)

```

```{r}
hunan <- st_read(dsn = "../In-class_Ex05/data/geospatial", 
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("../In-class_Ex05/data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_GDPPC<-left_join(hunan,hunan2012) %>%
  select(1:4,7,15)
```

```{r}

wm_q <- hunan_GDPPC %>%
  mutate(nb= st_contiguity(geometry),
         wt= st_weights(nb, style="W"),
         .before=1)
```

Performing Global Moran\`I permutation test

```{r}
set.seed(1234)
```

```{r}
global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim = 99)
```

Local  Moran`s I
```{r}


set.seed(1234)
lisa <- wm_q %>% 
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(local_moran)
```

```{r}
glimpse(lisa)
```


## Visualising Lisa map 
```{r}
lisa <- lisa %>%
  mutate(
    LISA_cluster = ifelse(
      p_ii_sim < 0.05,
      as.character(mean), 
      "Insignificant"),
    LISA_cluster = factor(
      LISA_cluster,
      levels = c("Insignificant", "Low-Low", "Low-High", "High-Low", "High-High")
    )
  )
```

```{r}
lisa_map <- tm_shape(lisa) + 
  tm_polygons(
    fill = "LISA_cluster",
    fill.scale = tm_scale_categorical(
      values = c(
        "grey80",      # Insignificant
        "blue",        # Low-Low
        "lightblue",   # Low-High
        "pink",        # High-Low
        "red"          # High-High
      )
    ),
    fill.legend = tm_legend(
      title = "LISA Cluster",
      position = tm_pos_in("left", "bottom"))
  ) +
  tm_borders() +
  tm_title("Local Moran's I Clusters (p < 0.05)")
lisa_map
```

